/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import logica.Servicio;
import model.Multa;
import model.Respuesta;


/**
 *
 * @author diego
 */
public class Registro extends javax.swing.JFrame implements Observer {

    ArrayList<Multa> lstMultas = new ArrayList<>();
    ArrayList<String> lstTipoMultas = new ArrayList<>();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
             
        txtFecha.setText(fechaActual());
       
        initComponents2();
        Servicio servicio = new Servicio();
        lstMultas = servicio.getMultas();
        lstTipoMultas = servicio.getTiposMulta();
        if(lstMultas == null) {
            System.err.println("La lista es null");
        } else {
            System.err.println("LISTA: "+lstMultas.size());
        }
        llenarTabla(lstMultas);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMultas = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPunto = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lbDniError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        rbtbusqueda = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mjborrados = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI");

        jLabel2.setText("Tipo");

        jLabel3.setText("Monto");

        jLabel4.setText("Correo");

        tbMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "DNI", "Multa", "Monto", "Correo", "Puntos", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMultas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbMultas);

        btnBorrar.setText("Borrar");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Punto");

        btnRefresh.setText("Refrescar");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lbDniError.setForeground(new java.awt.Color(255, 51, 51));

        jLabel6.setText("Fecha");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        rbtbusqueda.setText("Activar Busqueda");

        jMenu1.setText("Ventana");

        jMenuItem2.setText("Cerrar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        mjborrados.setText("Editar");

        jMenuItem1.setText("Borrados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mjborrados.add(jMenuItem1);

        jMenuBar1.add(mjborrados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMonto)
                                            .addComponent(lbDniError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtbusqueda)))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(btnRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)))
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtbusqueda))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbDniError)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnBorrar)
                            .addComponent(btnRefresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void initComponents2() {
        txtDNI.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }

            public void warn() {
                String dni = txtDNI.getText();
                validarDNI(dni);
            }
        });
        txtDNI.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }

            public void warn() {
         
                if(rbtbusqueda.isSelected()){
                   
                String busqueda = txtDNI.getText();
                if(busqueda.length() == 0) {
                    llenarTabla(lstMultas);
                    return;
                }
                buscador(busqueda);
            }}
        });
      
    }
public static String fechaActual(){
    
    Date fecha=new Date();
    SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
    
    return formatoFecha.format(fecha);
    
}
    
    private void buscador(String busqueda) {
        Predicate<Multa> byDni = multa -> multa.getDni().contains(busqueda);
        Predicate<Multa> byMulta = multa -> multa.getMulta().toLowerCase().contains(busqueda.toLowerCase());
        Predicate<Multa> byCorreo = multa -> multa.getCorreo().toLowerCase().contains(busqueda.toLowerCase());
        ArrayList<Multa> listaFiltradaDNI   = (ArrayList) lstMultas.stream().filter(byDni).collect(Collectors.toList());
        ArrayList<Multa> listaFiltradaMulta = (ArrayList) lstMultas.stream().filter(byMulta).collect(Collectors.toList());
        ArrayList<Multa> listaFiltradaCorreo = (ArrayList) lstMultas.stream().filter(byCorreo).collect(Collectors.toList());
        listaFiltradaDNI.addAll(listaFiltradaMulta);
        listaFiltradaDNI.addAll(listaFiltradaCorreo);
        llenarTabla(listaFiltradaDNI);
        
    }
    
    private void validarDNI(String dni) {
        btnRegistrar.setEnabled(false);
        if(dni.length() == 0) {
            lbDniError.setText(null);
            return;
        }
        if(!dni.matches("[0-9]+")) {
            lbDniError.setText("El número de DNI es incorrecto.");
            return;
        } else {
            lbDniError.setText(null);
        }
        if(dni.length() != 8) {
            lbDniError.setText("El número de DNI tiene que ser 8 caracteres.");
            return;
        } else {
            lbDniError.setText(null);
        }
        btnRegistrar.setEnabled(true);
    }
    
    int idMultaModif = 0;
    
    private void setearDatos() {
        String dni    = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 1  )+"";
        String multa  = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 2  )+"";
        String monto  = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 3 )+"";
        String correo = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 4  )+"";
        String punto  = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 5  )+"";
        String idMulta = tbMultas.getModel().getValueAt(tbMultas.getSelectedRow(), 0  )+"";
        System.err.println(idMulta+" - "+dni+" - "+multa+" - "+monto+" - "+correo+" - "+punto);
        idMultaModif = Integer.parseInt(idMulta);
        txtDNI.setText(dni);
        txtDNI.setEnabled(false);
        cmbTipos.setSelectedItem(multa);
        txtMonto.setText(monto);
        txtCorreo.setText(correo);
        txtPunto.setText(punto);
        btnRegistrar.setText("Actualizar");
        btnBorrar.setEnabled(true);
    }
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Estas seguro de borrar la multa?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            Servicio servicio = new Servicio();
            Respuesta rpta = new Respuesta();
            rpta = servicio.borrarMulta(idMultaModif);
            System.err.println(rpta.toString());
            if(rpta.getCodigo() == 0) {
                for(Multa m : lstMultas) {
                    if(m.getIdMulta() == idMultaModif) {
                        lstMultas.remove(m);
                        break;
                    }
                }
                idMultaModif = 0;
                limpiarForm();
                llenarTabla(lstMultas);
            }
            JOptionPane.showMessageDialog(this, rpta.getMsj());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Servicio servicio = new Servicio();
        lstMultas = servicio.getMultas();
        llenarTabla(lstMultas);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            String dni = txtDNI.getText();
            if(cmbTipos.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this,"Seleccione un Tipo de Multa correspondiente");
                return;
            }
            if(!dni.matches("[0-9]+")) {
                lbDniError.setText("El número de DNI es incorrecto.");
                return;
            }
            if(dni.length() != 8) {
                lbDniError.setText("El número de DNI tiene que ser 8 caracteres.");
                return;
            }
            String multa  = cmbTipos.getSelectedItem().toString();
            String montoTexto = txtMonto.getText();
            // validar
            
            String correo = txtCorreo.getText();
            int punto     = Integer.parseInt(txtPunto.getText());
            String fecha  = txtFecha.getText();
            
            Date fechaMulta = new SimpleDateFormat("dd/MM/yyyy").parse(fecha);  
            
            Double monto  = Double.parseDouble(montoTexto);
            
            Multa objMulta = new Multa();
            objMulta.setDni(dni);
            objMulta.setMulta(multa);
            objMulta.setMonto(monto);
            objMulta.setCorreo(correo);
            objMulta.setPunto(punto);
            objMulta.setFecha(fechaMulta);

            Servicio servicio = new Servicio();
            Respuesta rpta = new Respuesta();
            if(idMultaModif == 0) {
                rpta = servicio.insertarMultaProcedure(objMulta);
                objMulta.setIdMulta(rpta.getIdGenerado());
            } else {
                objMulta.setIdMulta(idMultaModif);
                rpta = servicio.ActualizarMultaProcedure(objMulta);
            }
            System.err.println(rpta.toString());
            if(rpta.getCodigo() == 0) {
                if(idMultaModif == 0) {
                    lstMultas.add(objMulta);
                } else {
                    for(Multa m : lstMultas) {
                        if(m.getIdMulta() == objMulta.getIdMulta()) {
                            m.setCorreo(correo);
                            m.setMonto(monto);
                            m.setMulta(multa);
                            m.setPunto(punto);
                            break;
                        }
                    }
                }
                idMultaModif = 0;
                limpiarForm();
                llenarTabla(lstMultas);
            }
            JOptionPane.showMessageDialog(this, rpta.getMsj());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    Borrados frame = new Borrados();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void limpiarForm() {
        txtDNI.setText(null);
        cmbTipos.setSelectedIndex(0);
        txtMonto.setText(null);
        txtCorreo.setText(null);
        txtPunto.setText(null);
        btnRegistrar.setText("Registrar");
        btnBorrar.setEnabled(false);
        txtDNI.setEnabled(true);
    }
    
    private void llenarTabla(ArrayList<Multa> lista) {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "DNI", "Multa", "Monto", "Correo", "Punto", "#"}, 0);
        int i = 1;
        for(Multa m : lista) {
            model.addRow(new Object[]{ m.getIdMulta(), m.getDni(), m.getMulta(), m.getMonto(), m.getCorreo(), m.getPunto(),i});
            i++;
        }
        tbMultas = new JTable(model);
        tbMultas.removeColumn(tbMultas.getColumnModel().getColumn(6));
        ListSelectionListener lel = new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(!event.getValueIsAdjusting()) {
                    setearDatos();
                }
            }
        };
        tbMultas.getSelectionModel().addListSelectionListener(lel);
        jScrollPane1.setViewportView(tbMultas);
    }
    
    @Override
        public void update(Observable o, Object arg) { // RECIBO LO ENVIADO POR EL changeData()
        Multa multRest = (Multa) arg;
        Servicio servicio = new Servicio();
        Respuesta rpta = new Respuesta();
        rpta = servicio.insertarMultaProcedure(multRest);
        multRest.setIdMulta(rpta.getIdGenerado());
        if(rpta.getCodigo() == 0) {
            lstMultas.add(multRest);
            limpiarForm();
            llenarTabla(lstMultas);
        }
        JOptionPane.showMessageDialog(this, rpta.getMsj());
    }
    /**
     * @param args the command line arguments
     */
    
    static Registro regiInstance = new Registro();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                regiInstance.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDniError;
    private javax.swing.JMenu mjborrados;
    private javax.swing.JRadioButton rbtbusqueda;
    private javax.swing.JTable tbMultas;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPunto;
    // End of variables declaration//GEN-END:variables

   /* boolean setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
*/
}
